### ISSUE TITLE
Pushed node_modules

### ISSUE THREAD

**Issue by finnhodgkin** [FAC-11/jaam-todo-list#21]
Easy mistake to make. 
![whatsthatcommit](https://user-images.githubusercontent.com/22300773/27951481-089678d6-62fd-11e7-8cb6-c0553efcd113.gif)

Just remember to initialise your repo with a node gitignore.
![initialise](https://user-images.githubusercontent.com/22300773/27951525-2d88b550-62fd-11e7-8153-641815d33fd5.gif)

**Comment by ameliejyc** [comment]
Those are some scary numbers 😄  

Thanks for pointing it out!
