### ISSUE TITLE
Great job with the tests!

### ISSUE THREAD

**Issue by finnhodgkin** [FAC-11/jaam-todo-list#24]
If you'd commented out the sort todos function and added an `/* istanbul ignore next */ ` before the final `if (module !==` statement you'd be 100% with all branches.

Sweeet! :+1:

**Comment by finnhodgkin** [comment]
Only thing I'd say is that the comments above the tests are a little irrelevant because tests have inbuilt comments:

https://github.com/FAC-11/jaam-todo-list/blob/master/test.js#L86-L110

**Comment by ameliejyc** [comment]
Interesting, I think @Jen-Harris is saying the opposite to your second comment in #23 ? Clash of opinions 😆

Thank you for the sort todo advice, will look at it now and check istanbul.
