### ISSUE TITLE
Perhaps 'marked0' should be the 'actual' in L156-L182

### ISSUE THREAD

**Issue by Jen-Harris** [FAC-11/jaam-todo-list#25]
Perhaps the 'marked0' should be the 'actual' and the output function may not need to be assigned a variable: 
```   var actual = logic.markTodo(markedO, 0);  ```

Rather this variable can become the actual: 
``` 
var markedO = [{
  | id: 0,
  | description: 'add chilli',
  | done: false,
  | },
  | {
  | id: 1,
  | description: 'onion',
  | done: true,
  | }
  | ]
```
Review the code [here #L156-L182](https://github.com/FAC-11/jaam-todo-list/blob/0e06a69087eedb43e4a3db3d1be920d00cbcc8fe/test.js#L156-L182)

**Comment by ameliejyc** [comment]
Thanks for the explanation on this Jen and Bart!
