### ISSUE TITLE
Address mobile usability 

### ISSUE THREAD

**Issue by Jen-Harris** [FAC-11/jaam-todo-list#27]
Perhaps insert meta viewport in html in order to prevent scaling on mobile:
``` <meta name="viewport" content="width=device-width, initial-scale=1.0"> ```

Currently becomes v small in mobile devices

**Comment by oliverjam** [comment]
Just came to raise this :)

More info here: https://developer.mozilla.org/en/docs/Mozilla/Mobile/Viewport_meta_tag

**Comment by ameliejyc** [comment]
Thank you - I've added the meta viewport and added some media queries in the css to make some font sizes and a button bigger.

**Comment by oliverjam** [comment]
@ameliejyc Nice one, looks great :)
